<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <title>
        WebService description of exported classes and methods
    </title>
    <style>
        body {
            margin: 0;
            padding: 0;
            font-family: Verdana;
        }

        #main {
            width: 90%;
            display: block;
            margin: auto;
        }

        #header {
            width: 100%;
            display: block;
            border: 2px solid #FFF;
            margin-left: -2px;

            height: 80px;
            margin-top: 20px;

            color: #FFF;
            font-weight: bold;

            font-size: 25px;
            line-height: 80px;
            text-indent: 20px;

            text-shadow: 0px 0px 3px #FFF;
            filter: dropshadow(color = #000000, offx = 0, offy = 0);

            -moz-box-shadow: 0 0 4px 4px #888;
            -webkit-box-shadow: 0 0 4px 2px #888;
            box-shadow: 0 0 4px 2px #888;

            border-radius: 8px;
            -moz-border-radius: 8px;
            -webkit-border-radius: 8px;

            background-image: linear-gradient(bottom, rgb(33, 178, 3) 9%, rgb(60, 214, 29) 63%, rgb(90, 255, 56) 99%);
            background-image: -o-linear-gradient(bottom, rgb(33, 178, 3) 9%, rgb(60, 214, 29) 63%, rgb(90, 255, 56) 99%);
            background-image: -moz-linear-gradient(bottom, rgb(33, 178, 3) 9%, rgb(60, 214, 29) 63%, rgb(90, 255, 56) 99%);
            background-image: -webkit-linear-gradient(bottom, rgb(33, 178, 3) 9%, rgb(60, 214, 29) 63%, rgb(90, 255, 56) 99%);
            background-image: -ms-linear-gradient(bottom, rgb(33, 178, 3) 9%, rgb(60, 214, 29) 63%, rgb(90, 255, 56) 99%);

            background-image: -webkit-gradient(linear, left bottom, left top, color-stop(0.09, rgb(33, 178, 3)), color-stop(0.63, rgb(60, 214, 29)), color-stop(0.99, rgb(90, 255, 56)));

        }

        table#table-of-contents {
            width: 100%;
        }

        table#table-of-contents td {
            padding: 0;
            margin: 0;
            width: 33%;
            vertical-align: top;
        }

        table#table-of-contents td h3 {
            font-size: 14px;
            font-weight: bold;
            border-bottom: 1px solid #6495ed;
            color: #6495ed;
            width: 80%;
            margin-left: 10%;
        }

        table#table-of-contents td ul {
            padding: 0;
            margin: 0;
            list-style: none;
            margin-left: 10%;
        }

        table#table-of-contents td li {
            margin: 0;
            padding: 0;
        }

        table#table-of-contents td li a {
            color: #696969;
        }

        #main h1 {
            font-size: 25px;
            margin-top: 20px;
            margin-bottom: 0;
            padding: 0;
            float: left;
            clear: both;
            color: #483d8b;
        }

        #namespaces {
            border: 1px solid #a9a9a9;
            padding: 0;
            margin: 0;
            list-style: none;
            padding-top: 10px;
            padding-bottom: 10px;
            padding-left: 10px;
            padding-right: 10px;
            float: left;
            clear: both;

            margin-top: 10px;

            -moz-box-shadow: 0 0 10px 1px #ccc;
            -webkit-box-shadow: 0 0 10px 1px #ccc;
            box-shadow: 0 0 10px 1px #ccc;

            border-radius: 8px;
            -moz-border-radius: 8px;
            -webkit-border-radius: 8px;
        }

        #namespaces a {
            color: #a9a9a9;
            text-decoration: none;
        }

        #namespaces a:hover {
            text-decoration: underline;
        }

        .class {
            margin-top: 50px;
        }

        .class h2 {
            margin: 0;
            padding: 0;
            border-bottom: 1px solid #6495ed;
            color: #6495ed;
            font-size: 24px;
            margin-bottom: 10px;
        }

        .class h3 {
            margin: 0;
            padding: 0;
            color: #083772;
            font-size: 16px;
            margin-top: 50px;
        }

        .class h4 {
            margin: 0;
            padding: 0;
            font-size: 16px;
            color: #444444;
            margin-left: 20px;
            margin-top: 20px;
        }

        p {
            color: #484848;
            font-size: 13px;
            margin: 0;
            margin-left: 20px;
            margin-top: 5px;
            margin-bottom: 5px;
        }

        ul.parameters {
            margin: 0;
            padding: 0;
            margin-left: 20px;
            margin-top: 10px;
            padding-left: 40px;
            list-style: disc;
        }

        ul.parameters li {
            font-size: 13px;
        }

        .parameter-name {
            color: #660000;
        }

        .parameter-type {
            color: #0464BB;
        }

        .parameter-description {
            color: #484848;
        }


    </style>
</head>
<body>
<div id="main">
    <div id="header">
        WebService description of exported classes and methods
    </div>
    <?php if (count($namespaces) > 1) { ?>
    <h1>Namespaces</h1>
    <ul id="namespaces">
        <?php foreach ($namespaces as $ns) { ?>
        <li><a
            href="/describe/<?php if ($ns) { ?><?php echo str_replace('\\', '/', $ns); ?><?php } ?>"><?php echo $ns ? : 'Global namespace'?></a>
        </li>
        <?php } ?>
    </ul>
    <?php } ?>
    <h1>Classes from <?php if ($namespace) { ?>namespace <?php echo $namespace; ?> <?php } else { ?>global
        namespace<?php } ?></h1>
    <table id="table-of-contents">
    <tr>
        <?php $i = 0; foreach ($description as $class => $methods) { ?>
        <td>
            <h3>
                <?php echo $class; ?>
            </h3>
            <ul>
                <?php foreach ($methods as $method => $details) { ?>
                <li><a href='#<?php echo $class;?>_<?php echo $method;?>'><?php echo $method; ?></a></li>
                <?php } ?>
            </ul>
        </td>
        <?php
        $i++;
        if ($i != 0 && $i % 3 == 0) {
            ?></tr><tr><?php
        }
    } ?>
        <?php
        if ($i < 3) {

            $i = 3 - $i;
            while ($i > 0) {
                ?>
                <td></td><?php
                $i--;
            }
        }
        ?>
    </tr>

    </table>

    <?php foreach ($description as $class => $methods) { ?>
    <div class='class'>
        <h2><?php echo $class;?></h2>

        <?php foreach ($methods as $method => $details) { ?>
        <a name="<?php echo $class;?>_<?php echo $method;?>"></a>
        <h3><?php echo $class;?>::<?php echo $method;?></h3>

        <?php if ($details['description']) { ?>
            <p><?php echo $details['description'];?></p>
            <?php } ?>
        <?php if ($details['parameters']) { ?>
            <h4>Parameters</h4>
            <ul class="parameters">
                <?php foreach ($details['parameters'] as $parameter) { ?>
                <li>
                    <span class="parameter-name">$<?php echo $parameter['name'];?></span>
                    <span class="parameter-type"><?php echo $parameter['type'];?></span>
                    <span class="parameter-description"> <?php echo $parameter['description'];?></span>
                </li>
                <?php }?>
            </ul>
            <?php } ?>


        <?php if ($details['return']) { ?>
            <h4>Returns</h4>
            <p>
                <span class="parameter-type"><?php echo $details['return']['type'];?></span>
                <span class="parameter-description"> <?php echo $details['return']['description'];?></span>
            </p>
            <?php } ?>
        <?php } ?>

    </div>
    <?php } ?>

</div>


<?php /*
    <div class="contents">
        <h1 class="section-title">Contents</h1>
        <?php foreach ($description as $class => $methods) { ?>
        <div class="class">
            <h1 class="class-name"><?php echo $class;?></h1>
            <?php foreach ($methods as $method => $details) { ?>
            <a href="#<?php echo $class;?>_<?php echo $method; ?>"><?php echo $method; ?></a>
            <?php } ?>
        </div>
        <?php } ?>

    </div>
*/?>

<?php /*foreach ($description as $class => $methods) { ?>
        <div class="class">
            <h1 class="class-name"><?php echo $class;?></h1>
            <?php foreach ($methods as $method => $details) { ?>
            <a name="<?php echo $class;?>_<?php echo $method; ?>"></a>

            <h2 class="method-name"><?php echo $class;?>::<?php echo $method; ?></h2>

            <p><?php echo nl2br($details['description']); ?></p>
            <?php if (count($details['parameters']) > 0) { ?>
                <h3>Parameters:</h3>
                <ul class="parameters">
                    <?php foreach ($details['parameters'] as $parameter) { ?>

                    <li>
                        <span class="parameter-name">$<?php echo $parameter['name'];?></span>
                        <span class="parameter-type"><?php echo $parameter['type'];?></span>
                        <span class="parameter-description"> <?php echo $parameter['description'];?></span>
                    </li>
                    <?php }?>
                </ul>
                <?php } ?>
            <h3>Returns:</h3>

            <p>
                <?php if ($details['return']) { ?>
                <span class="parameter-type"><?php echo $details['return']['type'];?></span>
                <span class="parameter-description"> <?php echo $details['return']['description'];?></span>
                <?php } else { ?>
                <span class="parameter-type">void</span>
                <?php } ?>
            </p>
            <?php } ?>
        </div>
        <?php } */?>


</div>
</div>

</body>
</html>